name: "Art Directive"
description: "To report a case related to artwork and art direction."
labels: [ "Type/Artwork", "State/Discussion" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Please provide a short description of what you are looking forward to
        have.
      placeholder: "E.g: I want a soup to be presented as smiling kitty cat face."
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior
      description: >
        Please specify the expected behavior of your request feature below. You
        may upload your associated artworks and presentations here.
      placeholder: "E.g: something like this one (attached sketch file)."
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: >
        Please specify the any current behavior (e.g. workarounds).You may
        specify "Not Applicable" when it's not applicable.
      placeholder: "E.g: no art. A bit boring."
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Associated Data Files
      description: >
        Please drag and drop all the necessary data files (e.g. screenshot,
        logs, etc) into the box below. Each successful uploads will transform
        into their unique URL link on its own.
      placeholder: "Please drag and drop it here."
    validations:
      required: false
