name: "Communities"
description: "To report a case solely related to the project's communities."
labels: [ "Type/Communities", "State/Discussion" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Please provide a short description of what you are looking forward to
        have.
      placeholder: "E.g: I want a rave and party with people man!"
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior
      description: >
        Please specify the expected behavior below of your request feature.
      placeholder: "E.g: Good food, good drink; make the atmosphere lively."
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: >
        Please specify the any current behavior (e.g. workarounds).You may
        specify "Not Applicable" when it's not applicable.
      placeholder: "E.g: no workaround. Need to spice things up a little."
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Associated Data Files
      description: >
        Please drag and drop all the necessary data files (e.g. screenshot,
        logs, etc) into the box below. Each successful uploads will transform
        into their unique URL link on its own.
      placeholder: "Please drag and drop it here."
    validations:
      required: false
