name: "Question"
description: "To query something about the project."
labels: [ "Type/Question", "State/Discussion" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Please provide a short description of your query.
      placeholder: "E.g: what's that delicious meat in the meal?"
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Researched Artifacts [COMPULSORY]
      description: >
        Please list out all your research artifacts you did (e.g. link,
        blog posts, documentations, etc) below. It is for us to gauge your
        context and current efforts. You can drag and drop all the necessary
        data files (e.g. screenshot, logs, etc) into the box for quick upload.
        Each successful uploads will transform into their unique URL link on
        its own.

        **NOTE: We may not reply you and will close the ticket with
        perjuidice if this section remains empty or unconvincing**.
      placeholder: "E.g: I did a lab report as attached. They can't tell."
    validations:
      required: true
